### ISSUE TITLE
Can't locate object method "create_message_headers" via package "Koha::Email" error when sending email from the Cart

### ISSUE THREAD

**Issue by lucyvh1** [ebsco/edsapi-koha-plugin#100]
I get the following error message when trying to send the contents of the Koha cart by email. 

Can't locate object method "create_message_headers" via package "Koha::Email" at /var/lib/koha/plugins/Koha/Plugin/EDS/opac/2005/opac-sendbasket.pl line 78.

Using plugin version 20.05002 with Koha 20.11.04.

**Comment by amitebsco** [comment]
Reproduce the issue.

<img width="1017" alt="Screen Shot 2021-05-27 at 19 31 36" src="https://user-images.githubusercontent.com/82651664/119840054-44438100-bf22-11eb-9f2b-8ebad5bc503c.png">

**Comment by amitebsco** [comment]
Cart email issue is fixed and ready for review. Please review @mmabrahamson @cambw
