### ISSUE TITLE
EDSScript.js StartEDS() "basketcount" is used incorrectly

### ISSUE THREAD

**Issue by minusdavid** [ebsco/edsapi-koha-plugin#11]
"basketcount" is used incorrectly as a variable at https://github.com/ebsco/edsapi-koha-plugin/blob/master/Koha/Plugin/EDS/js/EDSScript.js#L100-L101.

The only reason it's not "undefined" is because jquery creates a variable "basketcount" as there is an HTML element with an ID of "basketcount". If you console.log(basketcount), you'll get the HTML element and not the actual count.

We actually want to use "basketCount()" which is a function defined in basket.js. That way, we're comparing the contents of the "bib_list" cookie with the "bib_list" in local storage. Or we could not bother doing a comparison and just execute "updateBasket" since it seems we're already overriding the "bib_list" cookie at this stage.

**Comment by alvetm** [comment]
Basket update works fine with EDS integration and there was no need manually intervene with the update function at the plugin level although it appeared necessary at the time... the basket count check and update basket lines are commented out in the latest version.
//if(basketcount!=jbib_list.split('/').length-1)
						//updateBasket(jbib_list.length-1);

thanks for taking a look.

**Comment by minusdavid** [comment]
Sounds good. 

You could also comment out the following line:

if (basketcount == "") basketcount = 0;

As I mentioned in the issue, "basketcount" is a HTML element rather than the actual basket count. So this line doesn't really do anything except change a variable (created by jQuery I believe) from [HTML Element] to 0.
