### ISSUE TITLE
Plugin will not start in Koha 21.11

### ISSUE THREAD

**Issue by ricofreak** [ebsco/edsapi-koha-plugin#119]
To recreate:
-Upload lastest version: 21.11001
-Restart plack/memcached
-Configure plugin -> Save changes
-Launch the OPAC and nothing happens 
-If I try running SetEDS('en') or SetEDS('default') from the console I see errors:
Uncaught ReferenceError: Cookies is not defined

**Comment by ricofreak** [comment]
This looks to be related to Koha Bug 29940:

https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=29940

js-cookie/js.cookie-3.0.1.min.js is not included in Koha 21.11 until version 21.11.05. The plugin will not work on lower versions of 21.11.x

**Comment by mmabrahamson** [comment]
Thanks for catching this.  I was looking for the point where they officially changed it as well.  For this case, I'd suggest updating Koha 21.11 to a version past 21.11.05 to use the plugin.  I'll add this to the notes on the main page.
