### ISSUE TITLE
EDSScript.js StartEDS()  updateBasket(jbib_list.length-1) uses string instead of array

### ISSUE THREAD

**Issue by minusdavid** [ebsco/edsapi-koha-plugin#12]
As I mentioned on wizzyrea's issue, "updateBasket(jbib_list.length-1)" is actually using the length of the "bib_list" string coming from local storage rather than the length of the array created by splitting that string on the slash.

https://github.com/ebsco/edsapi-koha-plugin/blob/master/Koha/Plugin/EDS/js/EDSScript.js#L102

**Comment by minusdavid** [comment]
The plot thickens!

Sometimes the bib_list in jStorage is a string and sometimes it's an array!

If you add/remove on the search result page (opac-search.pl), it'll add/remove as strings.

However, if you add 2 records to the cart, open the cart, and remove one item, the "bib_list" value in local storage will now be an array!!!

**Comment by minusdavid** [comment]
Four examples of "bib_list" being set:

1) $.jStorage.set("bib_list",QueryString('bib_list'),{TTL:edsConfig.cookieexpiry*60*1000});
2) $.jStorage.set("bib_list","",{TTL:edsConfig.cookieexpiry*60*1000}); // added this line
3) $.jStorage.set("bib_list",$.cookie("bib_list"),{TTL:edsConfig.cookieexpiry*60*1000});
4) $.jStorage.set("bib_list",$.cookie("bib_list"),{TTL:edsConfig.cookieexpiry*60*1000});

2-4 treat "bib_list" as a string, but 1 treats it as an array. Of course, it's worth noting that it puts the whole querystring in as a single array element.

**Comment by minusdavid** [comment]
It looks like "document.cookie = 'bib_list='+jbib_list;" works with jbib_list as a string or an array, because the interpreter coerces the array into a string when concatenating the values.

But naturally "jbib_list.split" will work on a string but not an array...

And "basketcount" will be defined in opac-search.pl because the jquery populates that variable with an HTML object, whereas in opac-basket.pl, it's undefined.,, so the cookie will be reset on opac-search.pl regardless of whether or not "bib_list" is a string or an array... but the updateBasket in that block will never work... because jbib_list.split will fail for an array... and if a string is used it will update the basket count with the length of the string because of "updateBasket(jbib_list.length-1);"

I figure it makes more sense to just handle bib_list as a string. 

Of course, since the local storage never expires, it's probably necessary to include some data type detection when doing $.jStorage.get("bib_list")....

**Comment by alvetm** [comment]
Thanks for looking into this.

These 2 lines are now commented out in the latest version which fixed cart count.
//if (basketcount != jbib_list.split('/').length - 1)
               //updateBasket(jbib_list.length -1);

bib_list is stored in jStorage because the cookie path/scope is /cgi-bin/koha/ but the plugin path/scope is plugin/Koha/Plugin/EDS/opac/ so the cart values are not accessible.
Wanted to avoid changing the path of bib_list to / as it could have unintended consequences.
