### ISSUE TITLE
Cannot send opac baskets in Koha 21.11

### ISSUE THREAD

**Issue by ricofreak** [ebsco/edsapi-koha-plugin#121]
In Koha 21.11, with the EDS plugin installed I a unable to send a baket/cart.

To recreate:
1. With EDS installed, configured, and enabled to to the OPAC.
2. Add some items to your cart, either via a standard Koha search or from an EDS search
3.  Click on cart to go to 'cgi-bin/koha/opac-basket.pl'
4. Try sending the basket and notice the 500 error
5. Disable EDS
6. Repeat steps 2-4 but this time it will work without error.
7. 
The plack error logs tell you something like:

[Fri Jun 17 15:22:49.084571 2022] [cgi:error] [pid 116935] [client 172.20.21.36:40008] AH01215: Useless use of private variable in void context at /var/lib/koha/kohadev/plugins/Koha/Plugin/EDS/opac/2011/opac-sendbasket.pl line 200.: /var/lib/koha/kohadev/plugins/Koha/Plugin/EDS/opac/2011/opac-sendbasket.pl, referer: https://cleveland.bywatersolutions.com/cgi-bin/koha/opac-basket.pl?bib_list=260/
[Fri Jun 17 15:22:49.085184 2022] [cgi:error] [pid 116935] [client 172.20.21.36:40008] AH01215: Useless use of anonymous hash ({}) in void context at /var/lib/koha/kohadev/plugins/Koha/Plugin/EDS/opac/2011/opac-sendbasket.pl line 200.: /var/lib/koha/kohadev/plugins/Koha/Plugin/EDS/opac/2011/opac-sendbasket.pl, referer: https://cleveland.bywatersolutions.com/cgi-bin/koha/opac-basket.pl?bib_list=260/

**Comment by mmabrahamson** [comment]
I've added an update on #122 .  Please install the KPZ file from that PR and test it to verify.

**Comment by kidclamp** [comment]
From our partner testing:
My testing didn't result without error unfortunately.  I DO get the email window prompt, which is different from an instant error screen, however, after entering my email and hitting send the Error 500 screen dislplays.

**Comment by mmabrahamson** [comment]
When I ran into a similar issue during our own testing, it was because we hadn't configured everything properly to allow emails to be sent from the server.  Can you confirm that the server has been configured for sending emails and all appropriate ports are open?

**Comment by kidclamp** [comment]
I tested and was able to send a cart, provided it contained EDS/Discovery items

For a cart with only Koha items I receive the error:
Error sending mail: empty basket at /var/lib/koha/cleveland/plugins/Koha/Plugin/EDS/opac/2111/opac-sendbasket.pl line 163.: /var/lib/koha/cleveland/plugins/Koha/Plugin/EDS/opac/2111/opac-sendbasket.pl

It looks like this may be the problem:
        if($biblionumber =~m/\_\_/){($record,$dat)= ProcessEDSCartItems($biblionumber,$eds_data,$record,$dat);} #EDS Patch
        next unless $dat;

All koha biblionumebrs are skipped, and the $iso2709 variable is never populated, so we hit:
    if ( !defined $iso2709 ) {
        carp "Error sending mail: empty basket";
        $template->param( error => 1 );
    }

**Comment by mmabrahamson** [comment]
I made an additional update.  You were right that it was around that part and I just needed to move my check on $dat to after I processed catalog records if there were no EDS records.  Would you mind testing again?

**Comment by hartlinee** [comment]
Initial testing with the update does successfully send the cart! Partner testing is ongoing, I'll update with any relevant findings. Thank you!

**Comment by mmabrahamson** [comment]
Thanks!  I'm going to close this for now and merge the PR.  Let us know if there's anything else that comes up.
