### ISSUE TITLE
Cannot download cart in Koha 22.11

### ISSUE THREAD

**Issue by kidclamp** [ebsco/edsapi-koha-plugin#131]
"GetMarcBiblio" is not exported by the C4::Biblio module: /var/lib/koha/karachi/plugins/Koha/Plugin/EDS/opac/2111/opac-sendbasket.pl, referer:

Should use:

my $biblio_object = Koha::Biblios->find( $biblionumber );
my $record = $biblio_object->metadata->record;

**Comment by mmabrahamson** [comment]
Apologies on the extreme delay on this one.  The short version is the person who had been looking into this last year is no longer with the company and we have started looking into this again this week.  We're hoping to get this updated to 23.11 in the next couple months, followed by testing in 24.05 and eventually 24.11 when it's ready.

**Comment by mmabrahamson** [comment]
Hello!  We've just issues a PR to resolve this issue in 23.11.  Please feel free to test it here: #138

**Comment by mmabrahamson** [comment]
#138 fixes issues in 23.11.
