### ISSUE TITLE
Cannot send cart from OPAC in 22.11

### ISSUE THREAD

**Issue by kidclamp** [ebsco/edsapi-koha-plugin#132]
GetMarcAuthors has been removed, see the reference Koha bug below:
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=27266

**Comment by mmabrahamson** [comment]
Hello!  We've just issues a PR to resolve this issue in 23.11.  Please feel free to test it here: #138

**Comment by mmabrahamson** [comment]
#138 fixes carts in 23.11.
