### ISSUE TITLE
Use of Update button when filtering clears previously selected filters

### ISSUE THREAD

**Issue by lucyvh1** [ebsco/edsapi-koha-plugin#136]
When using 'Refine your search' options it does not seem possible to combine more than one filter at a time. To reproduce:

Go to https://library.marjon.ac.uk/cgi-bin/koha/opac-main.pl
Switch to Discovery and search for 'Stonehenge'
Filter to: Limit to = Full text
When results appear add another filter for Source type = Academic Journals
The floating 'Update' button will appear, click to update
Filtered results display but the previous Limit to = Full text filter has been unticked.

Plugin version is 22.11001, Koha version 22.11.12

**Comment by mmabrahamson** [comment]
Thanks for reporting this.  We're looking into it.

**Comment by omuzzyEBSCO** [comment]
Addressed issue in #137 - thank you for reporting this issue.
