### ISSUE TITLE
Plugin fails on Koha master

### ISSUE THREAD

**Issue by MagnusEnger** [ebsco/edsapi-koha-plugin#15]
https://github.com/ebsco/edsapi-koha-plugin/blob/master/Koha/Plugin/EDS.pm#L6 has this:

use C4::Branch;

but this module has been moved to Koha::Library/Libraries: 

Bug 15294 - Move the C4::Branch related code to Koha::Libraries - part 1
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=15294

So it looks like the plugin will need an update to work with current Kohas.

**Comment by joubu** [comment]
It seems that only C4::Context is used, that means the 3 other uses could/should be removed:
use C4::Branch;
use C4::Members;
use C4::Auth;

**Comment by alvetm** [comment]
Thank you. A patch release is now available that contains fix for this issue.
eds_plugin_16.1101.kpz
A new branch for Koha v16.11+ will be created soon.
