### ISSUE TITLE
Detailed Error Description Invalid IP

### ISSUE THREAD

**Issue by schnydszch** [ebsco/edsapi-koha-plugin#17]
Hi Alvet! I'm trying to configure in a Koha ILS 3.22.x EDS plugin version 3.2205 and I am getting the following errors "{"DetailedErrorDescription":"InvalidÂ IP.","ErrorDescription":"Invalid IP","ErrorNumber":"139"}" whenever I update the information. I tried the IP address of local computers and the IP address of my internet connection using GetLocalIP. Whenever I click the Update info, a new tab is opened and leads me to the IP address of my opac without the ":", i.e. http//domainname.of.opac/plugin/Koha/Plugin/EDS/opac/eds-raw.pl?q=info. There was no username and password set also, does that matter? Thanks in advance!

**Comment by alvetm** [comment]
Instructions updated in version 16110x+

/*****
User Name:	
*User Name with permission to access the EDS API. This is in EBSCO Admin, Authentication tab
Password:	
*Password with permissions to access the EDS API. This is in EBSCO Admin, Authentication tab.
******/

Yes, username and password are required for IP access too. There is a separate IP addresses field that allows access based on IP matches.
