### ISSUE TITLE
defaultsearch parameter from configuration doesn't seem to be loading on page

### ISSUE THREAD

**Issue by WNickC** [ebsco/edsapi-koha-plugin#18]
When changing the defaultsearch we don't seem to see this data populated into to page:

Worked around using this in opacuserjs:

// Uncomment the following line to re-enable EDS plugin in the opac.
$.getScript("/plugin/Koha/Plugin/EDS/js/EDSScript.js");
// This overrides the defaultsearch param in plugin config which doesn't seem to be working
$("head").append("<div id='eds-app' data-edsselecttext='Discovery' data-defaultsearch='koha'></div>");

**Comment by alvetm** [comment]
great tip! no need to patch plugin anymore in version16.110X+.
Plugin inserts and removes code in opacuserjs to enable/disable plugin via configure screen.
Code used is

/*eds{*/var defaultSearch="eds";$(document).ready(function(){$.ajax({url:"/plugin/Koha/Plugin/EDS/js/EDSScript.js",dataType:"script",cache:true}); });/*}eds*/

defaultSearch variable is either set to eds or koha depending on selection.
