### ISSUE TITLE
can't install plugin on koha 3.14.x

### ISSUE THREAD

**Issue by jsicot** [ebsco/edsapi-koha-plugin#2]
Hi,
I would like to test this plugin, but can not install it on Koha 3.14.x.
KPZ is uploaded but nothing appears then, only the message "No plugins installed".

koha-conf and koha-httpd are well configured as described [here] (http://manual.koha-community.org/3.12/en/pluginsystem.html) and syspref UseKohaPlugins is enabled :-(

Any assistance would be greatly appreciated.
Thanks in advance.
Julien

**Comment by alvetm** [comment]
Hi,

You might find the below URL useful too. Provides more info on how to enable/setup the plugin feature.

http://kohageek.blogspot.com.au/search/label/plugins

Cheers,
Alvet

**Comment by alvetm** [comment]
Also, the below URL contains a list of other plugins you can try to install and see if plugins in Koha is setup correctly.

http://bywatersolutions.com/koha-plugins/

**Comment by jsicot** [comment]
Hi,
Thanks for your reply.
I had already read this link. No one help me.

The problem was that Module::Bundled::Files was not installed on our instance...
We have installed it and the plugin is now ok.

Thanks again,
Julien

**Comment by alvetm** [comment]
Thanks for the update - glad its working :)
