### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by whitewabbit** [ebsco/edsapi-koha-plugin#23]
It's not working on koha common stable.

**Comment by MagnusEnger** [comment]
Maybe some more details will make it easier to figure out the problem?

**Comment by whitewabbit** [comment]
i think it's not compatible to the version?

**Comment by alvetm** [comment]
More details on the plugin compatibility is on the plugin home page. Here are the latest details as of 17/Feb/18 but please refer to the github landing page for more details.

use branch:master for Koha 17.05+ (includes latest features and updates)

use the branch:KohaV16.11x for Koha 16.11x (depricated)

user branch:Koha-v3.22.1x-to-Koha-v16.05.0x for Koha3.22.1 to Koha v16.05 (depricated)

user branch:Koha-v3.16.x-to-Koha-v3.22.0x for Koha3.16 to Koha v3.22 (depricated)

use the branch:KohaV3.14x for Koha 3.14x (depricated)

use the branch:KohaV3.12x for Koha 3.12x (depricated)

minimum Koha version required is Koha 3.12 with plugins enabled
