### ISSUE TITLE
Document changes to Apache config? 

### ISSUE THREAD

**Issue by MagnusEnger** [ebsco/edsapi-koha-plugin#24]
To get the OPAC scripts to do anything I had to add this to my Apache site config:

```
   ScriptAlias /plugin/Koha/Plugin/EDS/opac /var/lib/koha/prv/plugins/Koha/Plugin/EDS/opac
   Alias /plugin "/var/lib/koha/prv/plugins"
   # The stanza below is needed for Apache 2.4+
   <Directory /var/lib/koha/prv/plugins>
      Options Indexes FollowSymLinks
      AllowOverride None
      Require all granted
   </Directory>
```

Is that considered to be part of enabling plugins in Koha, or should it be documented somewhere?

**Comment by alvetm** [comment]
There is some documentation on Apache-Setup in the wiki for Debian and Ubuntu.
https://github.com/ebsco/edsapi-koha-plugin/wiki/Apache-Setup

Thanks for sharing this config too Magnus - I have added a link from that Wiki entry to this issue too.
