### ISSUE TITLE
custom.js 404

### ISSUE THREAD

**Issue by MagnusEnger** [ebsco/edsapi-koha-plugin#26]
When viewing the OPAC with the plugin enabled, there is an attempt at loading http://example.com/plugin/Koha/Plugin/EDS/js/custom/custom.js but since this file does not exist, it results in a 404 status.

**Comment by Kaustubh26** [comment]
Not able to replicate this issue in the latest release. Could you kindly verify if this is still happening?

**Comment by MagnusEnger** [comment]
What do you mean by the "latest release"? This?
https://github.com/ebsco/edsapi-koha-plugin/blob/master/eds_plugin_17.05.kpz

**Comment by MagnusEnger** [comment]
I can confirm that https://prv.bibkat.se/plugin/Koha/Plugin/EDS/js/custom/custom.js gives a normal 100 response after upgrading to https://github.com/ebsco/edsapi-koha-plugin/blob/master/eds_plugin_17.05.kpz 

Thanks!
