### ISSUE TITLE
Updates for 17.05

### ISSUE THREAD

**Issue by WNickC** [ebsco/edsapi-koha-plugin#27]
We need a second version for 17.05, in:
/var/lib/koha/model/plugins/Koha/Plugin/EDS/opac/eds-search.pl
line 389, the function GetItemTypes has been removed

replace it with:
        my $itemtypes = Koha::ItemTypes->search_with_localization;
        my %itemtypes = map { $_->{itemtype} => $_ } @{ $itemtypes->unblessed };

**Comment by wizzyrea** [comment]
I'm seeing this one as well, and have a client quite anxiously waiting on 17.05.

**Comment by Kaustubh26** [comment]
Hi, We have now updated the plugin to support Koha 17.05+. Could you kindly let us know whether the issues are resolved?
