### ISSUE TITLE
Error when trying to email cart

### ISSUE THREAD

**Issue by kylemhall** [ebsco/edsapi-koha-plugin#28]
After filling out the form to email the cart order and clicking the 'Submit' button, the following error occurs:

Software error:

Wrong CSRF token at /var/lib/koha/luther/plugins/Koha/Plugin/EDS/opac/1611/opac-sendbasket.pl line 58.
![send_book_cart_error](https://user-images.githubusercontent.com/50537/33491830-68ae9ac8-d689-11e7-81c3-24755ce88803.png)

**Comment by wizzyrea** [comment]
I'm seeing this problem as well. The plugin claims "no more patching" but I can't see how this would work without it.

**Comment by wizzyrea** [comment]
I'm seeing this issue as well.

**Comment by Kaustubh26** [comment]
We have done some updates to fix the cart issues in 17.11. Requesting if you could kindly test with now and let us know.

**Comment by kylemhall** [comment]
Getting the same error still.

**Comment by wizzyrea** [comment]
https://github.com/ebsco/edsapi-koha-plugin/pull/34 

This pull request, from Feb, ought to fix it.

**Comment by cameronbw** [comment]
Reviewing #34 today, thanks!

**Comment by cameronbw** [comment]
Thanks for the fix @wizzyrea all good on my end. I have a few more fixes this week so I'll hold off on rebuilding kpz

**Comment by wizzyrea** [comment]
👍 thanks!
