### ISSUE TITLE
EDSscript.js depends on cart (opacbookbag) being enabled

### ISSUE THREAD

**Issue by kidclamp** [ebsco/edsapi-koha-plugin#29]
If cart is disabled in 17.05 the 'Switch to catalogue' link ends up creating a blank drop down.

The issue seems to be in the ShowInfo function - without the cart it hangs/dies

**Comment by Kaustubh26** [comment]
We have done some updates to fix the cart issues in 17.11. Requesting if you could kindly test with now and let us know.

**Comment by mmabrahamson** [comment]
Closing issue as this is related to an unsupported version of Koha at this point.
