### ISSUE TITLE
EDS titles not added to cart

### ISSUE THREAD

**Issue by wizzyrea** [ebsco/edsapi-koha-plugin#30]
Since the plugin indicates no patching of core Koha files is required, I've omitted patching the cart on Koha 17.11, and EDS items don't seem to get added to the cart anymore.

**Comment by Kaustubh26** [comment]
We have done some updates to fix the cart issues in 17.11. Requesting if you could kindly test with now and let us know.

**Comment by wizzyrea** [comment]
Still having trouble here, and most recent .kpz doesn't include the Plugin directory so doesn't install correctly.

**Comment by Kaustubh26** [comment]
Apologies, just updated the .kpz file and tested. Let me know if you still face any issues. However, there are still some problems with the cart which seems to be working with Catalog items selected as well. We are working on this and will update.

**Comment by wizzyrea** [comment]
Thanks for that, I have two clients wanting this will be nice to tell them it's in progress. :)

**Comment by Kaustubh26** [comment]
The Cart and Send Email options have both been fixed now for EDS results and the plugin has been updated. Let us know if you still come across any issue.

**Comment by wizzyrea** [comment]
Thanks, looks to be working now!
