### ISSUE TITLE
No longer possible to change labels for 'Discovery'/'Catalogue'

### ISSUE THREAD

**Issue by kidclamp** [ebsco/edsapi-koha-plugin#31]
in previous versions it was possible to configure the wording in the search, can this functionality be restored?

**Comment by WNickC** [comment]
Hi Alvet,

How can we ensure these changes will remain over plugin updates/upgrades? Won't the file be overwritten?

**Comment by alvetm** [comment]
The plugin contains default.inc only. If the default language is en then you can download a copy of the english language and make changes there. Some of the supported languages are in the lang/ folder.
By making changes in en.inc you can ensure that the text will not change when the plugin is upgraded.

See how you go with that approach and let us know if there are any other concerns with this.
