### ISSUE TITLE
included scripts should use https

### ISSUE THREAD

**Issue by kidclamp** [ebsco/edsapi-koha-plugin#32]
For SSL sites we get an error on the tool setup, need to fetch the script below as https:

<script type="text/javascript" src="http://widgets.ebscohost.com/prod/common/javascript/gss-common.js"></script>

**Comment by minusdavid** [comment]
I think that particular URL is fixed now, but if you can find other URLs, Cam said that he's happy to fix them.

**Comment by jmaferreira** [comment]
Have you tried using the following instead? Should work in both cases.

```
<script type="text/javascript" src="//widgets.ebscohost.com/prod/common/javascript/gss-common.js"></script>
```

**Comment by minusdavid** [comment]
> Have you tried using the following instead? Should work in both cases.
> 
> ```js
> <script 
>    type="text/javascript" 
>    src="//widgets.ebscohost.com/prod/common/javascript/gss-common.js">
> </script>
> ```

I think historically the plugin has used that syntax, although there's really no reason not to just use HTTPS.

In any case, it's really just a matter of someone putting together a pull request for it. I'd say go for it : ).

**Comment by mmabrahamson** [comment]
This looks like it's resolved in the current version, but if you're still running into issues please feel free to reopen this issue!
