### ISSUE TITLE
Bad template paths on 17.11

### ISSUE THREAD

**Issue by kidclamp** [ebsco/edsapi-koha-plugin#35]
Change in the way paths are used in Koha

see this commit:
https://github.com/bywatersolutions/koha-plugin-coverflow/commit/6b8886cb4407f5043ea10aedd046003bb98daf31

I fixed with this:
my $PluginDir = C4::Context->config("pluginsdir");#dirname(abs_path($0));
$PluginDir .= "/Koha/Plugin/EDS";

**Comment by kylemhall** [comment]
This will work in 99% of cases, however, it's possible that config("pluginsdir") will return a list of dirs and not a scalar. In that case it will be necessary to check and find which path is correct for the plugin. 

This is a possible improvement:
my $pluginsdir = C4::Context->config("pluginsdir");
my @pluginsdir = ref($pluginsdir) eq 'ARRAY' ? @$pluginsdir : $pluginsdir;
my $PluginDir = grep { -f $_ . "/Koha/Plugin/EDS.pm" } @pluginsdir;

**Comment by cambw** [comment]
This was brought into one of the more recent updates, I'll credit you in #68 !

Thanks @kylemhall !
