### ISSUE TITLE
Patch to opac-downloadcart.pl doesn't detect active state of EDS Plugin

### ISSUE THREAD

**Issue by wizzyrea** [ebsco/edsapi-koha-plugin#4]
We noticed that the cart with the EDS patch applied exhibits the following problem when the EDS plugin is either not installed (well, duh, why would you have the patch then, amirite) or simply disabled (which is a more likely scenario).

It would be nice to have a check around the EDS code to make sure the EDS plugin is enabled. Such an addition might make it possible to upstream the changes to downloadcart to Koha, as well.

**Comment by alvetm** [comment]
Hi wizzyrea,

Check out the line just after #START EDS in the 2 patch files downloadcart and sendcart

I've wrapped EDS custom code with this condition so the code gets ignored if the plugin is disabled.
if(eval{C4::Context->preference('EDSEnabled')}){

Is this what you were referring to?

Cheers,
Alvet

**Comment by alvetm** [comment]
Since plugin v3.1643 - all patches check to see if EDSEnabled = y before executing. This will prevent any errors from occurring if the plugin is not installed or disabled.
