### ISSUE TITLE
gss.ebscohost.com/cwu/apps/mgt/gi.png should be served over HTTP

### ISSUE THREAD

**Issue by minusdavid** [ebsco/edsapi-koha-plugin#49]
At the moment gss.ebscohost.com/cwu/apps/mgt/gi.png is served over HTTP which gives you the following warning in the browser console:

"Mixed Content: The page at 'https://xxxxxxx.xxx/' was loaded over HTTPS, but requested an insecure image 'http://gss.ebscohost.com/cwu/apps/mgt/gi.png'. This content should also be served over HTTPS."

I've noticed there is a HTTPS version available, so there's no reason not to use it. I'll send a pull request in a moment.

**Comment by minusdavid** [comment]
Actually, glancing through the source code, I think there are many HTTP URLs where there could probably be HTTPS URLs instead...

**Comment by minusdavid** [comment]
But this particular one is the only one that jumps out at me at the moment as a user.

**Comment by cameronbw** [comment]
Fixed!
Let me know if you find more examples. I've tried to update any URLs I've come across .
