### ISSUE TITLE
Remote Content (Integrated Search Connectors)

### ISSUE THREAD

**Issue by jbarker022** [ebsco/edsapi-koha-plugin#5]
Are there plans to include "Remote Content (Integrated Search Connectors)" Databases as a widget or similar to the way it is displayed in the EDS Search from EBSCO? Also is this the right place to ask this question? Sorry if it isn't.

**Comment by alvetm** [comment]
There is a way to include Integrated Search Connectors as a widget via the customisation manager. 

https://github.com/ebsco/edsapi-koha-plugin/wiki/Customisation-Manager

Happy for you to raise a request with EBSCO support if you would like to explore this.

Cheers,
Alvet

**Comment by jbarker022** [comment]
No that's fine. But If I could get the full javascript code for that widget that would help a lot.

**Comment by alvetm** [comment]
Kindly contact EBSCO support or submit a request via EBSCO Apps & Cloud Services.Thanks.
https://orbit.ebsco.com/
