### ISSUE TITLE
https://widgets.ebscohost.com/prod/api/koha/apps/gtrans_maori.js contains encoding issue

### ISSUE THREAD

**Issue by minusdavid** [ebsco/edsapi-koha-plugin#51]
(I think it's been said that Cam already fixed this, but I haven't seen a fix come through in a while now.)

Looking at https://widgets.ebscohost.com/prod/api/koha/apps/gtrans_maori.js and I see the following:

#google_translate_element > .m::after {\
				content: "Translate to te reo MÃ„ori";\

In Koha, it actually shows up as "Translate to te reo MÄori"

Looks to me like an encoding issue. 

Looks like the UTF-8 hex for ā is 0xC4 0x81. Ä is 00C4 in Latin-1. Of course, Ã is 00C3 in Latin-1 but „ isn't a Latin-1 character; it's a UTF-8 character of 0xE2 0x80 0x9E and Ã is 0xC3 0x83 in UTF-8, so I'm not sure what's going up in the actual Javascript.

**Comment by cameronbw** [comment]
Weird! Display is fine on my end, I'll have another look at this.

**Comment by mmabrahamson** [comment]
This appears to be resolved, but please reopen if it's still an issue.
