### ISSUE TITLE
eds-raw.pl is rendered as text when Load setting from EBSCO Admin now button is clicked

### ISSUE THREAD

**Issue by schnydszch** [ebsco/edsapi-koha-plugin#57]
Hi! Using Koha 16.11, running over https, Debian 8 and using Plugin version 16.1103. Whenever I click the "Load setting from EBSCO Admin now" button, the eds-raw.pl is rendered as text. There must be a problem with my setting. I followed this: https://github.com/ebsco/edsapi-koha-plugin/wiki/Apache-Setup and this: https://github.com/ebsco/edsapi-koha-plugin/issues/24 but still not successful in getting rid of eds-raw not rendered as text. Any help? Thanks in advance!

**Comment by schnydszch** [comment]
When all the settings for the EDS API are all okay, it all becomes Okay and so the Koha ILS-EDS integration is now okay. But still, it's just weird that when the settings are not okay and "Load setting from EBSCO Admin now" button is clicked, the eds-raw.pl is rendered as text. Hmm..

**Comment by jmaferreira** [comment]
Hi @schnydszch. The same is happening to us. Which setting was offending your plugin?

**Comment by cambw** [comment]
Should be fixed in #68

**Comment by mmabrahamson** [comment]
This looks to be resolved with the 19.05 release to master, but please feel free to reopen if you install the new release and still see this issue.
