### ISSUE TITLE
Link to full text does not show for items that utilize EBSCO's Digital Archive Viewer

### ISSUE THREAD

**Issue by mkstephens** [ebsco/edsapi-koha-plugin#58]
Hello,
We own a couple of different historical archives collections (ATLA Historical Monographs, AAS Historical Periodicals). I recently discovered that when items from these collections appear in a Discovery search within Koha, the link to full text does not appear. Screen shots from an example are attached.
Are there plans to address this in a future release of the plugin?
In the meantime, would it help if I imported MARC records for these collections into Koha, or would that make it worse by causing duplication in Discovery search results? The biggest reason we have Discovery is so that I don't have to import MARC records into Koha for our electronic content.
Thanks for your help,
Myka Kennedy Stephens
Lancaster Theological Seminary
Lancaster, PA

![search results](https://user-images.githubusercontent.com/16354546/46807416-da0d4c00-cd37-11e8-9acb-3475fb25ecb4.png)
![koha detailed record](https://user-images.githubusercontent.com/16354546/46807420-dc6fa600-cd37-11e8-83c0-5718e0c787be.png)
![eds detailed record](https://user-images.githubusercontent.com/16354546/46807423-de396980-cd37-11e8-93c5-dff80021341c.png)

**Comment by dpodboy** [comment]
This appears to be an issue with the EDS API, so I've logged a case and service issue with the EBSCO Technical Support team. I replied to your email with additional information. We will track the resolution through that case.
