### ISSUE TITLE
Invalid IP

### ISSUE THREAD

**Issue by MagnusEnger** [ebsco/edsapi-koha-plugin#62]
Hi! 

I had a Koha installation where the EDS plugin was working nicely, but after some upgrades it does not work. I have narrowed the problem down to this:

When I go to the configure page, I enter the username, password, profileid and customerid, plus all the other information requested. Then I click on "Load setting from EBSCOadmin now", a small window appears and disappears, the button says to wait 10 seconds and then an error is displayed in the "ED settings" field: 

{"DetailedErrorDescription":"InvalidÂ IP.","ErrorDescription":"Invalid IP","ErrorNumber":"139"}

I also notice that the password field has changed. The customer's password contains a @, but this has disappeared! 

EBSCO Support has provided me with the information "In EBSCOAdmin you have the following IP addresses registered...", and I have entered them into the "IP Addresses" field. 

So I am confused as to which IP is invalid? Do I have to do the configuration from one of the IPs that are recognized as belonging to the customer? Can I enter my own IP into the IP field? Any clarification would be most welcome!

Best regards, 
Magnus Enger
Libriotech, Norway

**Comment by MagnusEnger** [comment]
Any thoughts on this?

**Comment by jmaferreira** [comment]
We have the same problem. Any updates?

**Comment by MagnusEnger** [comment]
The "Invalid IP"-error went away when EBSCO added the IP of the Koha server to their list of accepted IPs. Now I get the EDS Settings back from the server, but when I try to save the config form I get a 500 Internal Server Error.

**Comment by MagnusEnger** [comment]
Ah it looks like the 500 error does not matter. The config is saved and EDS works in the OPAC again! I suspect the 500 will be solved by #68.

**Comment by cambw** [comment]
I was going to circle back to this after the 1905 release is out but looks like you've found the solution. You can contact EBSCO support to get them to add the IP address to your EDS profile, or do it yourself [here](https://connect.ebsco.com/s/article/How-do-I-add-or-update-IP-addresses-in-EBSCOadmin-for-authentication?language=en_US). Shouldn't be a too common of an issue though.

Thanks!
