### ISSUE TITLE
require eds-methods.pl needs full path

### ISSUE THREAD

**Issue by kidclamp** [ebsco/edsapi-koha-plugin#63]
In Debian 9 the current path is not included by default, moving the line and using $PluginDir seems to fix

Must be done in both eds-search.pl and eds-raw.pl

my $PluginDir = C4::Context->config("pluginsdir");
$PluginDir = $PluginDir.'/Koha/Plugin/EDS';
require $PluginDir.'/opac/eds-methods.pl';

**Comment by Alex-Buckley** [comment]
Hi Nick, 

We noticed this problem as well. We have found adding ./ to the start of the filename in the require line in  eds-detail.pl, eds-ac.pl, eds-cite.pl, eds-raw.pl, eds-search.pl, pfi-search.pl fixes this issue so I have submitted a pull request with these fixes in it:

https://github.com/ebsco/edsapi-koha-plugin/pull/67

Cheers,
Alex

**Comment by cambw** [comment]
#68 incorporates this patch 👍

**Comment by mmabrahamson** [comment]
This looks to be resolved with the 19.05 release to master, but please feel free to reopen if you install the new release and still see this issue.
