### ISSUE TITLE
Can't make edsapi-koha-plugin work

### ISSUE THREAD

**Issue by schnydszch** [ebsco/edsapi-koha-plugin#69]
Hi! I'm getting the following error:
Software error:
Can't locate eds-methods.pl in @INC (@INC contains: /usr/share/koha/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /var/lib/koha/krc/plugins/Koha/Plugin/EDS/opac/eds-search.pl line 68.

Currently using Koha 18.05.14.000 Perl version 5.024001. eds_plugin_17.11006.kpz is the kpz version I'm trying to use. Lowered it to eds_plugin_17.11005.kpz but still it does not work. **eds_plugin_17.11005.kpz worked with 18.05.07.000 production server that we have.** Tested first with 19.05 and 18.11 but can't make it work hence lowering it to 18.05. Any idea on how to go about this issue?

**Comment by fridobox** [comment]
Maybe it is pull request #67 :

> We found that in Koha 18.11.x the Koha EDS plugin fails when you perform an EDS search it fails due to not being able to locate the eds-methods.pl. Adding ./ to the start of the require line fixes this problem.

**Comment by schnydszch** [comment]
Yeah, i implemented that pull request and curiously was able to make Koha EDS plugin work with 19.05.x. :)
