### ISSUE TITLE
A period is added after opac-detail.pl?biblionumber= when bibliographic details is clicked in eds-search.pl

### ISSUE THREAD

**Issue by schnydszch** [ebsco/edsapi-koha-plugin#75]
Hi all! Using Debian 9 and Koha 19.11. I'm getting error 404 when accessing the bibliographic details of records in eds-search.pl. It seems a period is being added in the URL, such that the url is "cgi-bin/koha/opac-detail.pl?biblionumber=.21412&resultid=1" instead of "cgi-bin/koha/opac-detail.pl?biblionumber=.21412&resultid=1". I'm trying to check the plugin where to edit the particular line but I don't know yet what to edit. Any kind soul who can lead me to what to edit. Thanks in advance!

**Comment by mmabrahamson** [comment]
Hi!  In your config file for the plugin, in the field "Catalogue AN Prefix", it needs to have a period at the end of the prefix.  Can you try updating it and see if that resolves your issue?

![Screen Shot 2020-05-07 at 12 08 10 PM](https://user-images.githubusercontent.com/9534243/81323789-8bcb4680-905b-11ea-8c40-8fe409bd4b7e.png)

**Comment by schnydszch** [comment]
Hi! That resolved the issue. Didn't see that part. Thanks! :)
