### ISSUE TITLE
Error when updating credentials

### ISSUE THREAD

**Issue by kidclamp** [ebsco/edsapi-koha-plugin#76]
When trying to update credentials in the config we get a 500 error on submitting the form

The issue appears to be that the edsinfo field contains unescaped quotes and is breaking form submission.

**Comment by mmabrahamson** [comment]
I confirmed this on my own test interface as well.  Looking into a few options to fix and hope to have a PR for it this week or next.

**Comment by mmabrahamson** [comment]
This should have been resolved in PR #84 .  If you update to the current version and still have this issue please let me know and we'll reopen this.
