### ISSUE TITLE
Issues loading plugin in IE, EDGE, Safari

### ISSUE THREAD

**Issue by kidclamp** [ebsco/edsapi-koha-plugin#86]
We are getting reports that on some browsers the dropdown does not correctly load.

After loading the selected option is "Switch to all resources"
If a user attempts to search, it fails. They must select "Library catalog" to search

**Comment by mmabrahamson** [comment]
We did see this issue in Safari and update the plugin to handle for it.  Which version of the plugin are you currently using?  19.05009 should resolve it, but definitely let me know if you still see issues after upgrading.

**Comment by kidclamp** [comment]
Ah, we were on 19.05007
