### ISSUE TITLE
Cannot send basket with Koha 19.05 & plugin 19.05009

### ISSUE THREAD

**Issue by AndrewIsh** [ebsco/edsapi-koha-plugin#91]
Upon trying to send the contents of the basket, we receive the following error:
`Undefined subroutine &main::decode_json called at /var/lib/koha/cust/plugins/Koha/Plugin/EDS/opac/eds-methods.pl line 521.`
Explicitly adding an import for `decode_json` alongside the existing `encode_json` import appears to fix the issue though, checking the mail logs, the mail is never sent. It is silently failing somehow as there are no errors in the log. 

Koha: 19.11.03.000 running Plack
Plugin: 19.05009

**Comment by mmabrahamson** [comment]
This should be resolved in eds_plugin_20.05002.kpz, which is compatible with 19.11.  Let us know if you have any issues!
