### ISSUE TITLE
Out of date templates with Koha 20.11

### ISSUE THREAD

**Issue by AndrewIsh** [ebsco/edsapi-koha-plugin#93]
As more and more of our customers move to 20.11 we're encountering problems with the template provided being out of date. Specifically, class names such as `row-fluid`, `span2` & `span10` are no longer used, so styles no longer correctly apply.

**Comment by efrierson** [comment]
Thanks for reporting this.  We'll be taking a look at this soon.

**Comment by amitebsco** [comment]
Started working will submit patches soon for review.

**Comment by amitebsco** [comment]
template issue with detail page (eds-detail.pl), advance search page (eds-search.pl)

**Comment by amitebsco** [comment]
Fixed template: eds-detail.pl, eds-search.pl, and result page.

**Comment by amitebsco** [comment]
Added to select multiple items from the search result page by clicking the option "select all" and add into the cart.
Given options "select all" and "clear all" on the search result page.
